services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: coming-soon-page
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./app:/usr/share/nginx/html
      - ./docker/configs/nginx:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge